name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          
      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn build
